# Generated by Django 6.0.5 on 2026-06-23 21:57

import containers.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0007_seed_status_workflows'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('customer_number', models.CharField(max_length=40)),
                ('org_number', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('billing_address', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_uid', models.CharField(default=containers.models.generate_qr_uid, editable=False, max_length=32, unique=True)),
                ('pin_hash', models.CharField(blank=True, default='', max_length=128)),
                ('container_type', models.CharField(choices=[('skip', 'Skip'), ('rolloff', 'Roll-off'), ('wheelie', 'Wheelie bin'), ('recycling', 'Recycling'), ('hazmat', 'Hazardous')], max_length=40)),
                ('size', models.CharField(blank=True, default='', max_length=40)),
                ('serial_number', models.CharField(blank=True, default='', max_length=80)),
                ('waste_category', models.CharField(blank=True, choices=[('household', 'Household'), ('construction', 'Construction'), ('electrical', 'Electrical'), ('asbestos', 'Asbestos'), ('mixed', 'Mixed')], default='', max_length=40)),
                ('status', models.CharField(choices=[('active', 'Active'), ('removed', 'Removed'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('placed_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='organizations.organization')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='containers.customer')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('license_class', models.CharField(blank=True, default='', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40)),
                ('source', models.CharField(choices=[('qr', 'QR portal'), ('portal', 'Portal'), ('phone', 'Phone'), ('import', 'Import'), ('api', 'API')], default='portal', max_length=20)),
                ('status', models.CharField(blank=True, default='', max_length=60)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, default='', max_length=120)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='containers.container')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='containers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='organizations.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('en_route', 'En route'), ('done', 'Done'), ('failed', 'Failed')], default='assigned', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='organizations.organization')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='containers.driver')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='containers.servicerequest')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, default='', max_length=40)),
                ('requires_pin', models.BooleanField(default=True)),
                ('default_sla_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_types', to='organizations.organization')),
                ('project_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.projecttype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='containers.servicetype'),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('street', models.CharField(max_length=255)),
                ('postal_code', models.CharField(blank=True, default='', max_length=16)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('municipality', models.CharField(blank=True, default='', max_length=120)),
                ('access_notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='containers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='organizations.organization')),
            ],
            options={
                'ordering': ['city', 'street'],
            },
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='containers.site'),
        ),
        migrations.AddField(
            model_name='container',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='containers', to='containers.site'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'name'], name='containers__organiz_c86ba1_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('organization', 'customer_number'), name='unique_customer_number_per_organization'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['organization', 'is_active'], name='containers__organiz_728273_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['driver', 'scheduled_date'], name='containers__driver__7b887d_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['service_request'], name='containers__service_43d3ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicetype',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_service_type_code_per_organization'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['organization', 'customer'], name='containers__organiz_fd7bdf_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['organization', 'status'], name='containers__organiz_e709ca_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['organization', 'scheduled_date'], name='containers__organiz_a23c1f_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['customer'], name='containers__custome_a8dd3e_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['container'], name='containers__contain_8cd89e_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicerequest',
            constraint=models.UniqueConstraint(fields=('organization', 'reference'), name='unique_service_request_reference_per_organization'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['organization', 'status'], name='containers__organiz_8ccf1d_idx'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['site'], name='containers__site_id_e10a51_idx'),
        ),
    ]
