# Generated by Django 6.0.5 on 2026-06-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('verified', 'Verified'), ('scheduled', 'Scheduled'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('invoice_ready', 'Invoice ready'), ('invoiced', 'Invoiced')], default='new', max_length=60),
        ),
    ]
