# Generated by Django 6.0.5 on 2026-06-23 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0003_servicerequestactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_status', models.CharField(max_length=60)),
                ('recipient', models.EmailField(max_length=254)),
                ('sent', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='containers.servicerequest')),
            ],
            options={
                'ordering': ['-created', '-id'],
            },
        ),
    ]
