# Generated by Django 6.0.5 on 2026-06-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0004_notificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
