# Generated by Django 6.0.5 on 2026-05-31 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_seed_project_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=60)),
                ('label', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('is_terminal', models.BooleanField(default=False)),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_definitions', to='organizations.projecttype')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('project_type', 'name'), name='unique_status_name_per_project_type')],
            },
        ),
    ]
