# Generated by Django 6.0.5 on 2026-05-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_project_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
