# Generated by Django 6.0.5 on 2026-05-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
